import { useRef } from 'react';
import { useHeroCombatActions } from '../useHeroCombatActions';
import { useArenaGridMovement } from '../useArenaGridMovement';
import { useCombatTurns } from '../useCombatTurns';
import { useOpportunityAttackResolver } from './useOpportunityAttackResolver';
import { useMonsterTurnAI } from '../useMonsterTurnAI';
import { useGameKeyboard } from '../useGameKeyboard';
import { useGameLifecycle } from '../useGameLifecycle';
import { useCanvasRenderer } from '../useCanvasRenderer';
import { useMinimapRenderer } from '../useMinimapRenderer';
import { getEntitySizeInSquares, getDistanceBetweenEntities, getDamageTypeColor } from '../../../../game/combatUtils';
import { RACES_REFERENCE } from '../../../../lib/api/references';

export interface UseArenaCombatControllerProps {
  character: any;
  onCharacterUpdated?: () => Promise<void> | void;
  gamePlatformState: any;
  handleExecuteCelestialRevelation: (type: 'Alma Radiante' | 'Consumo Radiante' | 'Mortalha Necrótica') => void;
  isHeroTurn: boolean;
  activeEntity: any;
}

export function useArenaCombatController({
  character,
  onCharacterUpdated,
  gamePlatformState,
  handleExecuteCelestialRevelation,
  isHeroTurn,
  activeEntity
}: UseArenaCombatControllerProps) {
  const {
    canvasRef,
    minimapRef,
    activeRevelation,
    setActiveRevelation,
    processDamageAndCheckKill,
    isSfxEnabled,
    biome,
    grid,
    setGrid,
    torches,
    entities,
    setEntities,
    activeEntityIndex,
    setActiveEntityIndex,
    currentTurnRound,
    setCurrentTurnRound,
    weather,
    weatherTime,
    combatDifficulty,
    isBattleOver,
    setIsBattleOver,
    setIsVictoryScreenVisible,
    setShowVictorySummaryModal,
    setVictoryData,
    droppedLoot,
    setDroppedLoot,
    chests,
    hazards,
    setHazards,
    powerups,
    setPowerUps,
    restPoints,
    setRestPoints,
    pendingRestPointId,
    setPendingRestPointId,
    totalGameTurns,
    setTotalGameTurns,
    setMovementStepsCount,
    mapStreak,
    lastEncounterPos,
    setLastEncounterPos,
    victoryLogged,
    prevHadVisibleMonstersRef,
    exploredCellsRef,
    collectLootItem,
    openChest,
    addLootItemToInventory,
    expandMapIfNeeded,
    rollAdvantageState,
    setRollAdvantageState,
    isNight,
    isIndoor,
    entitiesRef,
    getActiveFeats,
    getHeroLightRadiusInCells,
    heroHasBlindFighting,
    isEntityVisible,
    isEntityVisibleByBlindFightingOnly,
    getEntityCover,
    shouldHideEntityDetails,
    breathWeaponMaxUses,
    isGoliath,
    breathWeaponDetails,
    goliathAncestryMaxUses,
    isHalfling,
    isOrc,
    adrenalineRushMaxUses,
    secondWindMaxUses,
    actionSurgeMaxUses,
    rageMaxUses,
    channelDivinityMaxUses,
    spellSlotsMax,
    indomitableMaxUses,
    superiorityDiceMaxUses,
    bardicInspirationMaxUses,
    layOnHandsMaxPool,
    focusPointsMaxUses,
    wildShapeMaxUses,
    checkAmmunitionRequirement,
    getCharacterAmmoCount,
    consumeAmmunition,
    consumeThrownWeapon,
    highlightedPath,
    setHighlightedPath,
    selectedAttackIndex,
    setShowAttackModal,
    setShowTargetModal,
    setTargetCandidates,
    setPendingAttackInfo,
    setLatestRoll,
    setLatestInitiativeRoll,
    activeEffects,
    setActiveEffects,
    triggerAttackVisualEffect,
    characterAttacks,
    currentSelectedAttack,
    weaponMasteryInfo,
    breathWeaponUses,
    setBreathWeaponUses,
    setShowBreathWeaponModal,
    setBreathWeaponShape,
    setSelectedBreathTargets,
    secondWindUses,
    setSecondWindUses,
    healingHandsUses,
    setHealingHandsUses,
    celestialRevelationUses,
    setCelestialRevelationUses,
    draconicFlightUses,
    activeDraconicFlight,
    setActiveDraconicFlight,
    setDraconicFlightRoundsLeft,
    largeFormUses,
    activeLargeForm,
    setActiveLargeForm,
    setLargeFormRoundsLeft,
    setRadiantSoulRoundsLeft,
    setShowRevelationMenu,
    goliathAncestryUses,
    setGoliathAncestryUses,
    isTeleportTargetMode,
    setIsTeleportTargetMode,
    pendingTacticalMindInfo,
    setPendingTacticalMindInfo,
    setShowTacticalMindAlertModal,
    hasHeroicInspiration,
    setPendingHalflingLuckInfo,
    setPendingHeroicInspirationInfo,
    adrenalineRushUses,
    setAdrenalineRushUses,
    channelDivinityUses,
    setChannelDivinityUses,
    spellSlots,
    setSpellSlots,
    indomitableUses,
    setIndomitableUses,
    superiorityDiceUses,
    setSuperiorityDiceUses,
    bardicInspirationUses,
    setBardicInspirationUses,
    layOnHandsPool,
    setLayOnHandsPool,
    focusPointsUses,
    setFocusPointsUses,
    wildShapeUses,
    setWildShapeUses,
    recklessAttackActive,
    setRecklessAttackActive,
    gwmActive,
    sharpshooterActive,
    pendingOpportunityAttack,
    setPendingOpportunityAttack,
    floatingTexts,
    setFloatingTexts,
    addCombatLog,
    setPendingGoliathHitInfo,
    cols,
    rows,
    isFullscreenMap,
    is3dMode,
  } = gamePlatformState;

  const moveHeroDirectionRef = useRef<(dx: number, dy: number) => void>(() => {});

  // Hook de Ações de Combate do Herói
  const heroCombatActions = useHeroCombatActions({
    entities,
    setEntities,
    activeEntity,
    isHeroTurn,
    isBattleOver,
    character,
    currentSelectedAttack,
    characterAttacks,
    selectedAttackIndex,
    weaponMasteryInfo,
    biome,
    weather,
    isNight,
    torches,
    grid,
    activeAdvantageMode: rollAdvantageState,
    gwmActive,
    sharpshooterActive,
    activeLargeForm,
    isGoliath,
    goliathAncestryUses,
    isHalfling,
    hasHeroicInspiration,
    isOrc,
    adrenalineRushUses,
    adrenalineRushMaxUses,
    healingHandsUses,
    celestialRevelationUses,
    channelDivinityUses,
    channelDivinityMaxUses,
    breathWeaponUses,
    breathWeaponDetails,
    spellSlots,
    spellSlotsMax,
    secondWindUses,
    secondWindMaxUses,
    indomitableUses,
    indomitableMaxUses,
    recklessAttackActive,
    bardicInspirationUses,
    bardicInspirationMaxUses,
    layOnHandsPool,
    layOnHandsMaxPool,
    focusPointsUses,
    focusPointsMaxUses,
    wildShapeUses,
    wildShapeMaxUses,
    superiorityDiceUses,
    superiorityDiceMaxUses,
    pendingTacticalMindInfo,
    isSfxEnabled,
    addCombatLog,
    triggerAttackVisualEffect,
    setLatestRoll,
    processDamageAndCheckKill,
    moveHeroDirection: (dx: number, dy: number) => moveHeroDirectionRef.current(dx, dy),
    consumeThrownWeapon,
    setDroppedLoot,
    checkAmmunitionRequirement,
    getCharacterAmmoCount,
    consumeAmmunition,
    getActiveFeats,
    getHeroLightRadiusInCells,
    isEntityVisible,
    setRollAdvantageState,
    setPendingGoliathHitInfo,
    setTargetCandidates,
    setPendingAttackInfo,
    setShowTargetModal,
    setShowAttackModal,
    setPendingHalflingLuckInfo,
    setPendingHeroicInspirationInfo,
    setFloatingTexts,
    setAdrenalineRushUses,
    setHealingHandsUses,
    setCelestialRevelationUses,
    setShowRevelationMenu,
    handleExecuteCelestialRevelation,
    setChannelDivinityUses,
    setSelectedBreathTargets,
    setBreathWeaponShape,
    setShowBreathWeaponModal,
    setBreathWeaponUses,
    setActiveEffects,
    setSpellSlots,
    setSecondWindUses,
    setPendingTacticalMindInfo,
    setShowTacticalMindAlertModal,
    setIndomitableUses,
    setRecklessAttackActive,
    setBardicInspirationUses,
    setLayOnHandsPool,
    setFocusPointsUses,
    setWildShapeUses,
    setSuperiorityDiceUses,
  });

  // Movimentação em Grid
  const {
    checkGridTriggers,
    moveHeroDirection,
    handleCellClick,
  } = useArenaGridMovement({
    entities,
    setEntities,
    grid,
    activeEntityIndex,
    isHeroTurn,
    isBattleOver,
    character,
    activeLargeForm,
    isHalfling,
    secondWindUses,
    hasHeroicInspiration,
    isTeleportTargetMode,
    isGoliath,
    isSfxEnabled,
    biome,
    weather,
    isNight,
    torches,
    currentSelectedAttack,
    hazards,
    setHazards,
    powerups,
    setPowerUps,
    restPoints,
    setRestPoints,
    droppedLoot,
    chests,
    addCombatLog,
    setFloatingTexts,
    triggerAttackVisualEffect,
    setLatestRoll,
    processDamageAndCheckKill,
    processHeroAttackExecution: heroCombatActions.processHeroAttackExecution,
    collectLootItem,
    openChest,
    setPendingHalflingLuckInfo,
    setPendingHeroicInspirationInfo,
    setPendingTacticalMindInfo,
    setShowTacticalMindAlertModal,
    setPendingRestPointId,
    setIsTeleportTargetMode,
    setGoliathAncestryUses,
    setMovementStepsCount,
    setTotalGameTurns,
    isEntityVisible,
    getHeroLightRadiusInCells,
    expandMapIfNeeded,
  });

  moveHeroDirectionRef.current = moveHeroDirection;

  // Turnos de Combate
  const { advanceTurn } = useCombatTurns({
    entities,
    setEntities,
    activeEntityIndex,
    setActiveEntityIndex,
    currentTurnRound,
    setCurrentTurnRound,
    isBattleOver,
    setIsBattleOver,
    setIsVictoryScreenVisible,
    grid,
    torches,
    biome,
    weather,
    isNight,
    character,
    activeLargeForm,
    activeDraconicFlight,
    activeRevelation,
    setActiveDraconicFlight,
    setDraconicFlightRoundsLeft,
    setActiveLargeForm,
    setLargeFormRoundsLeft,
    setActiveRevelation,
    setRadiantSoulRoundsLeft,
    addCombatLog,
    triggerAttackVisualEffect,
    setLatestRoll,
    processDamageAndCheckKill,
    checkGridTriggers,
    currentSelectedAttack,
    getHeroLightRadiusInCells,
    setHighlightedPath,
    setShowTargetModal,
    setPendingAttackInfo,
  });

  // Ataques de Oportunidade
  const { handleResolveOpportunityAttack } = useOpportunityAttackResolver({
    pendingOpportunityAttack,
    setPendingOpportunityAttack,
    entities,
    setEntities,
    grid,
    torches,
    getHeroLightRadiusInCells,
    addCombatLog,
    triggerAttackVisualEffect,
    setLatestRoll,
    processDamageAndCheckKill,
    checkGridTriggers,
    advanceTurn
  });

  // IA dos Monstros
  useMonsterTurnAI({
    activeEntity,
    activeEntityIndex,
    isBattleOver,
    entities,
    entitiesRef,
    setEntities,
    grid,
    biome,
    isNight,
    torches,
    character,
    activeLargeForm,
    currentSelectedAttack,
    getHeroLightRadiusInCells,
    advanceTurn,
    addCombatLog,
    triggerAttackVisualEffect,
    setLatestRoll,
    processDamageAndCheckKill,
    checkGridTriggers,
    onTriggerOpportunityAttack: setPendingOpportunityAttack,
  });

  // Teclado
  useGameKeyboard({
    isHeroTurn,
    isBattleOver,
    activeEntity,
    grid,
    entities,
    moveHeroDirection,
  });

  // Ciclo de Vida do Jogo
  useGameLifecycle({
    entities,
    setEntities,
    activeEntityIndex,
    setActiveEntityIndex,
    character,
    getActiveFeats,
    addCombatLog,
    setLatestInitiativeRoll,
    isBattleOver,
    setIsBattleOver,
    prevHadVisibleMonstersRef,
    torches,
    isNight,
    biome,
    droppedLoot,
    setDroppedLoot,
    collectLootItem,
    chests,
    openChest,
    addLootItemToInventory,
    setVictoryData,
    setShowVictorySummaryModal,
    setActiveRevelation,
    victoryLogged,
    mapStreak,
    activeLargeForm,
    onCharacterUpdated,
    lastEncounterPos,
    setLastEncounterPos,
    combatDifficulty,
    grid,
    setGrid,
    restPoints,
    advanceTurn,
    isEntityVisible,
    shouldHideEntityDetails,
  });

  // Renderizador do Canvas
  useCanvasRenderer({
    canvasRef,
    grid,
    entities,
    activeEntityIndex,
    biome,
    isNight,
    weather,
    weatherTime,
    torches,
    character,
    activeEffects,
    floatingTexts,
    droppedLoot,
    chests,
    hazards,
    powerups,
    restPoints,
    cols,
    rows,
    isFullscreenMap,
    activeRevelation,
    isTeleportTargetMode,
    isGoliath: isGoliath || false,
    is3dMode,
    nightProgress: isNight ? 1 : 0,
    highlightedPath,
    activeLargeForm,
    getEntitySizeInSquares,
    RACES_REFERENCE,
    activeEntity,
    getEntityCover,
    shouldHideEntityDetails,
    getDamageTypeColor,
    isIndoor: isIndoor || false,
    heroHasBlindFighting,
    heroEntity: entities.find(e => e.type === 'hero'),
    getHeroLightRadiusInCells,
    isEntityVisible,
    isEntityVisibleByBlindFightingOnly,
    getDistanceBetweenEntities
  });

  // Renderizador do Minimapa
  useMinimapRenderer({
    minimapRef,
    grid,
    entities,
    biome,
    weather,
    cols,
    rows,
    isFullscreenMap,
    isNight,
    getHeroLightRadiusInCells,
    heroHasBlindFighting,
    exploredCellsRef,
    isEntityVisible,
  });

  return {
    heroCombatActions,
    moveHeroDirection,
    handleCellClick,
    checkGridTriggers,
    advanceTurn,
    handleResolveOpportunityAttack
  };
}
