import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  CombatEntity,
  CombatLog,
} from '../../../game/types';
import { isTwoHandedWeaponLocal, isLightWeapon } from '../../../game/combatEngine';
import { useHeroCapabilities } from "./useHeroCapabilities";
import { useArenaExploration } from "./useArenaExploration";
import { useSurvivalNeeds } from "./useSurvivalNeeds";
import { useGameSettings } from "./useGameSettings";
import { useFloatingTexts } from "./useFloatingTexts";
import { useCharacterResources } from "./useCharacterResources";
import { useDayNightCycle } from "./platform/useDayNightCycle";
import { useArenaViewport } from "./platform/useArenaViewport";
import { useCombatModalsState } from "./platform/useCombatModalsState";
import { useArenaVisualFX } from "./platform/useArenaVisualFX";
import { useHeroCombatStatsAndWeapons } from "./platform/useHeroCombatStatsAndWeapons";
import { useCombatDamageProcessor } from "./platform/useCombatDamageProcessor";
import { useHeroSpecialAbilitiesState } from "./platform/useHeroSpecialAbilitiesState";
import { useArenaAmbientSound } from "./platform/useArenaAmbientSound";
import { useHeroWeaponFeatsConfig } from "./platform/useHeroWeaponFeatsConfig";
import { useArenaCombatTargeting } from "./platform/useArenaCombatTargeting";
import { useProceduralExplorationBridge } from '../../../game/world/useProceduralExplorationBridge';

export interface UseGamePlatformStateProps {
  character: any;
  onExitGame: () => void;
  onCharacterUpdated?: () => Promise<void> | void;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export function useGamePlatformState({
  character,
  onExitGame,
  onCharacterUpdated,
  difficulty = 'medium'
}: UseGamePlatformStateProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const minimapRef = useRef<HTMLCanvasElement | null>(null);

  const [activeRevelation, setActiveRevelation] = useState<'Alma Radiante' | 'Consumo Radiante' | 'Mortalha Necrótica' | null>(null);

  const {
    isAmbientSoundEnabled,
    setIsAmbientSoundEnabled,
    isSfxEnabled,
    setIsSfxEnabled,
    isShowMinimap,
    setIsShowMinimap,
    isShowZoomControls,
    setIsShowZoomControls,
    proceduralWorldEnabled,
    setProceduralWorldEnabled
  } = useGameSettings();

  const proceduralBridge = useProceduralExplorationBridge({
    enabled: proceduralWorldEnabled,
    character,
  });

  const { floatingTexts, setFloatingTexts } = useFloatingTexts();

  const [logs, setLogs] = useState<CombatLog[]>([]);
  const addCombatLog = useCallback((
    actorName: string,
    title: string,
    detail: string,
    type: CombatLog['type'] | 'spell' = 'roll'
  ) => {
    const entry: CombatLog = {
      id: Date.now().toString() + Math.random(),
      timestamp: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }),
      actorName,
      title,
      detail,
      type: (type === 'spell' ? 'system' : type) as CombatLog['type']
    };
    setLogs(prev => [entry, ...prev]);
  }, []);

  // Ability state and max usage control encapsulated in useCharacterResources
  const resources = useCharacterResources({ character });
  const {
    secondWindUses,
    setSecondWindUses,
    healingHandsUses,
    setHealingHandsUses,
    celestialRevelationUses,
    setCelestialRevelationUses,
    draconicFlightUses,
    setDraconicFlightUses,
    activeDraconicFlight,
    setActiveDraconicFlight,
    draconicFlightRoundsLeft,
    setDraconicFlightRoundsLeft,
    largeFormUses,
    setLargeFormUses,
    activeLargeForm,
    setActiveLargeForm,
    largeFormRoundsLeft,
    setLargeFormRoundsLeft,
    goliathAncestryUses,
    setGoliathAncestryUses,
    adrenalineRushUses,
    setAdrenalineRushUses,
    relentlessEnduranceUses,
    setRelentlessEnduranceUses,
    hasHeroicInspiration,
    setHasHeroicInspiration,
    actionSurgeUses,
    setActionSurgeUses,
    rageUses,
    setRageUses,
    channelDivinityUses,
    setChannelDivinityUses,
    spellSlots,
    setSpellSlots,
    indomitableUses,
    setIndomitableUses,
    superiorityDiceUses,
    setSuperiorityDiceUses,
    bardicInspirationUses,
    setBardicInspirationUses,
    layOnHandsPool,
    setLayOnHandsPool,
    focusPointsUses,
    setFocusPointsUses,
    wildShapeUses,
    setWildShapeUses,
    luckyPoints,
    setLuckyPoints,
  } = resources;

  // Desacoplamento da Exploração de Arena (Procedural, Baús, Descansos e Recompensas)
  const arenaExploration = useArenaExploration({
    character,
    onCharacterUpdated,
    onExitGame,
    isSfxEnabled,
    addCombatLog,
    setFloatingTexts,
    secondWindMaxUses: resources.secondWindMaxUses,
    healingHandsMaxUses: resources.healingHandsMaxUses,
    celestialRevelationMaxUses: resources.celestialRevelationMaxUses,
    draconicFlightMaxUses: resources.draconicFlightMaxUses,
    largeFormMaxUses: resources.largeFormMaxUses,
    goliathAncestryMaxUses: resources.goliathAncestryMaxUses,
    adrenalineRushMaxUses: resources.adrenalineRushMaxUses,
    relentlessEnduranceMaxUses: resources.relentlessEnduranceMaxUses,
    isHuman: resources.isHuman,
    actionSurgeMaxUses: resources.actionSurgeMaxUses,
    rageMaxUses: resources.rageMaxUses,
    channelDivinityMaxUses: resources.channelDivinityMaxUses,
    spellSlotsMax: resources.spellSlotsMax,
    indomitableMaxUses: resources.indomitableMaxUses,
    superiorityDiceMaxUses: resources.superiorityDiceMaxUses,
    bardicInspirationMaxUses: resources.bardicInspirationMaxUses,
    layOnHandsMaxPool: resources.layOnHandsMaxPool,
    focusPointsMaxUses: resources.focusPointsMaxUses,
    wildShapeMaxUses: resources.wildShapeMaxUses,
    luckyMaxPoints: resources.luckyMaxPoints,
    setSecondWindUses,
    setHealingHandsUses,
    setCelestialRevelationUses,
    setDraconicFlightUses,
    setActiveDraconicFlight,
    setDraconicFlightRoundsLeft,
    setLargeFormUses,
    setActiveLargeForm,
    setLargeFormRoundsLeft,
    setGoliathAncestryUses,
    setAdrenalineRushUses,
    setRelentlessEnduranceUses,
    setHasHeroicInspiration,
    setActionSurgeUses,
    setRageUses,
    setChannelDivinityUses,
    setSpellSlots,
    setIndomitableUses,
    setSuperiorityDiceUses,
    setBardicInspirationUses,
    setLayOnHandsPool,
    setFocusPointsUses,
    setWildShapeUses,
    setLuckyPoints,
    setActiveRevelation,
    activeRevelation,
    activeLargeForm,
  });

  const {
    biome,
    setBiome,
    grid,
    setGrid,
    torches,
    setTorches,
    entities,
    setEntities,
    activeEntityIndex,
    setActiveEntityIndex,
    currentTurnRound,
    setCurrentTurnRound,
    weather,
    setWeather,
    weatherTime,
    setWeatherTime,
    isNightManual,
    setIsNightManual,
    combatDifficulty,
    setCombatDifficulty,
    isBattleOver,
    setIsBattleOver,
    isVictoryScreenVisible,
    setIsVictoryScreenVisible,
    showVictorySummaryModal,
    setShowVictorySummaryModal,
    victoryData,
    setVictoryData,
    droppedLoot,
    setDroppedLoot,
    chests,
    setChests,
    hazards,
    setHazards,
    powerups,
    setPowerUps,
    restPoints,
    setRestPoints,
    pendingRestPointId,
    setPendingRestPointId,
    totalGameTurns,
    setTotalGameTurns,
    movementStepsCount,
    setMovementStepsCount,
    lastMealTurn,
    lastShortRestTurn,
    lastLongRestTurn,
    prevTurns,
    mapStreak,
    setMapStreak,
    isSaving,
    setIsSaving,
    lastEncounterPos,
    setLastEncounterPos,
    processedDeathIdsRef,
    collectedLootIdsRef,
    openedChestIdsRef,
    exploredCellsRef,
    victoryLogged,
    prevHadVisibleMonstersRef,
    initNewCombat,
    addLootItemToInventory,
    collectLootItem,
    openChest,
    useRestPoint,
    useShortRestPoint,
    handleFinishExploration,
    handleClaimLootAndSave,
    expandMapIfNeeded,
  } = arenaExploration;

  const activeEntity = entities[activeEntityIndex];

  // Modificador de d20 para Ataque (Vantagem / Desvantagem / Normal)
  const [rollAdvantageState, setRollAdvantageState] = useState<'normal' | 'advantage' | 'disadvantage'>('normal');

  // Configuração do Grid, Zoom, Câmera e Viewport encapsulados no hook dedicado
  const {
    zoomLevel,
    setZoomLevel,
    handleZoomIn,
    handleZoomOut,
    handleZoomReset,
    is3dMode,
    setIs3dMode,
    isFullscreenMap,
    setIsFullscreenMap,
    isMinimapMinimized,
    setIsMinimapMinimized,
    safeZoom,
    cols,
    rows
  } = useArenaViewport();

  useSurvivalNeeds({
    totalGameTurns,
    prevTurns,
    biome,
    character,
    onCharacterUpdated,
    lastMealTurn,
    lastShortRestTurn,
    lastLongRestTurn,
    weather,
    addCombatLog,
  });

  // Ciclo de Dia e Noite encapsulado no hook dedicado
  const {
    isIndoor,
    isDesert,
    cycleIndex,
    isNightCycle,
    phaseTurn,
    totalMinutesElapsed,
    baseHour,
    totalMinutesFromMidnight,
    normalizedMinutes,
    currentHour,
    currentMinute,
    timeFormatted,
    nightProgress,
    isNight,
    setIsNight,
    timePhaseLabel,
    timePhaseIcon,
    timePhaseColor
  } = useDayNightCycle({
    totalGameTurns,
    isNightManual,
    setIsNightManual,
    biome,
    weather,
    setWeather,
    prevTurns,
    lastShortRestTurn,
    lastLongRestTurn,
    setTotalGameTurns,
    setMovementStepsCount
  });

  // Entidades e Combate
  const entitiesRef = useRef<CombatEntity[]>(entities);
  useEffect(() => {
    entitiesRef.current = entities;
  }, [entities]);

  // Hook desacoplado de capacidades, raças, classes e visão do herói
  const heroCapabilities = useHeroCapabilities({
    character,
    entities,
    grid,
    torches,
    biome,
    isNight,
    activeRevelation,
    onCharacterUpdated,
  });

  const {
    getActiveFeats,
    getHeroLightRadiusInCells,
    heroHasBlindFighting,
    isEntityVisible,
    isEntityVisibleByBlindFightingOnly,
    shouldHideEntityDetails,
    getEntityCover,
    isMonsterDefeated,
    shouldHideMonsterStats,
    isDragonborn,
    breathWeaponMaxUses,
    draconicFlightMaxUses,
    isGoliath,
    largeFormMaxUses,
    breathWeaponDetails,
    luckyMaxPoints,
    hasLuckyFeat,
    goliathAncestryMaxUses,
    isHalfling,
    isHuman,
    isOrc,
    adrenalineRushMaxUses,
    relentlessEnduranceMaxUses,
    isAasimar,
    healingHandsMaxUses,
    celestialRevelationMaxUses,
    secondWindMaxUses,
    actionSurgeMaxUses,
    rageMaxUses,
    channelDivinityMaxUses,
    spellSlotsMax,
    indomitableMaxUses,
    superiorityDiceMaxUses,
    bardicInspirationMaxUses,
    layOnHandsMaxPool,
    focusPointsMaxUses,
    wildShapeMaxUses,
    hasMagicCapability,
    hasSecondWindCapability,
    checkAmmunitionRequirement,
    getCharacterAmmoCount,
    consumeAmmunition,
    consumeThrownWeapon,
  } = heroCapabilities;

  // Estado de Ação e Seleção de Alvo no Grid
  const {
    selectedAction,
    setSelectedAction,
    targetEntityId,
    setTargetEntityId,
    highlightedPath,
    setHighlightedPath
  } = useArenaCombatTargeting({
    activeEntityIndex,
    entitiesRef,
    setEntities
  });

  // Estados de Modais e Reações encapsulados no hook dedicado
  const {
    showAttackModal,
    setShowAttackModal,
    showItemModal,
    setShowItemModal,
    showShortRestModal,
    setShowShortRestModal,
    pendingShortRestItem,
    setPendingShortRestItem,
    hitDiceToSpend,
    setHitDiceToSpend,
    showLootModal,
    setShowLootModal,
    showSettingsModal,
    setShowSettingsModal,
    showTacticalMindAlertModal,
    setShowTacticalMindAlertModal,
    pendingTacticalMindInfo,
    setPendingTacticalMindInfo,
    showRelentlessModal,
    setShowRelentlessModal,
    pendingRelentlessInfo,
    setPendingRelentlessInfo,
    pendingOpportunityAttack,
    setPendingOpportunityAttack,
    selectedEntityForPopup,
    setSelectedEntityForPopup,
    showTargetModal,
    setShowTargetModal,
    targetCandidates,
    setTargetCandidates,
    pendingAttackInfo,
    setPendingAttackInfo,
    latestRoll,
    setLatestRoll,
    latestInitiativeRoll,
    setLatestInitiativeRoll,
    showBreathWeaponModal,
    setShowBreathWeaponModal,
    breathWeaponShape,
    setBreathWeaponShape,
    selectedBreathTargets,
    setSelectedBreathTargets,
    showRevelationMenu,
    setShowRevelationMenu,
    isTeleportTargetMode,
    setIsTeleportTargetMode,
    pendingGoliathHitInfo,
    setPendingGoliathHitInfo,
    pendingGoliathDamageInfo,
    setPendingGoliathDamageInfo,
    pendingHalflingLuckInfo,
    setPendingHalflingLuckInfo,
    pendingHeroicInspirationInfo,
    setPendingHeroicInspirationInfo
  } = useCombatModalsState();

  // Estados para Ativar/Desativar penalidade e bônus de GWM ou Sharpshooter e Versátil
  const {
    gwmActive,
    setGwmActive,
    sharpshooterActive,
    setSharpshooterActive,
    versatileTwoHandedWeapons,
    setVersatileTwoHandedWeapons,
    isVersatileWeapon,
    getVersatileDamage
  } = useHeroWeaponFeatsConfig({
    getActiveFeats
  });

  // Efeito de Som Ambiente com Clima Atmosférico
  useArenaAmbientSound({
    biome,
    weather,
    isBattleOver,
    isAmbientSoundEnabled
  });

  // Refs de montagem inicial
  const isInitialMount = useRef<boolean>(true);

  // Efeitos visuais ativos no Grid e clima encapsulados no hook dedicado
  const {
    activeEffects,
    setActiveEffects,
    triggerAttackVisualEffect
  } = useArenaVisualFX({
    isSfxEnabled,
    setFloatingTexts,
    weather,
    setWeatherTime
  });

  // Estatísticas de combate, armas, CA e itens usáveis encapsulados no hook dedicado
  const {
    usableInventoryItems,
    totalRationsCount,
    characterAttacks,
    selectedAttackIndex,
    setSelectedAttackIndex,
    hasChangedWeaponThisTurn,
    setHasChangedWeaponThisTurn,
    currentSelectedAttack,
    heroACDetails,
    combatSummary,
    handleSelectWeapon,
    weaponMasteryInfo
  } = useHeroCombatStatsAndWeapons({
    character,
    entities,
    setEntities,
    activeEntityIndex,
    versatileTwoHandedWeapons,
    getActiveFeats,
    shouldHideEntityDetails,
    addCombatLog,
    isVersatileWeapon,
    getVersatileDamage
  });

  // Habilidades raciais, estados especiais de combate e contagens de voo
  const {
    radiantSoulRoundsLeft,
    setRadiantSoulRoundsLeft,
    breathWeaponUses,
    setBreathWeaponUses,
    recklessAttackActive,
    setRecklessAttackActive,
    itemQuantities,
    setItemQuantities,
    handleUseLuckyPoint,
    hasDamageAncestry
  } = useHeroSpecialAbilitiesState({
    character,
    entities,
    setEntities,
    activeEntityIndex,
    isBattleOver,
    activeRevelation,
    setActiveRevelation,
    activeDraconicFlight,
    setActiveDraconicFlight,
    setDraconicFlightRoundsLeft,
    activeLargeForm,
    breathWeaponMaxUses,
    goliathAncestryMaxUses,
    setGoliathAncestryUses,
    adrenalineRushMaxUses,
    setAdrenalineRushUses,
    relentlessEnduranceMaxUses,
    setRelentlessEnduranceUses,
    isHuman,
    setHasHeroicInspiration,
    luckyPoints,
    setLuckyPoints,
    luckyMaxPoints,
    setRollAdvantageState,
    usableInventoryItems,
    addCombatLog
  });

  // Processamento de dano, vantagens/desvantagens e mortes de combate
  const {
    activeAdvantageMode,
    impendingAttackDetails,
    processDamageAndCheckKill,
    isHeroDead
  } = useCombatDamageProcessor({
    character,
    entities,
    setEntities,
    entitiesRef,
    recklessAttackActive,
    rollAdvantageState,
    currentSelectedAttack,
    activeLargeForm,
    weather,
    isEntityVisible,
    shouldHideEntityDetails,
    getActiveFeats,
    addCombatLog,
    setFloatingTexts,
    processedDeathIdsRef,
    mapStreak,
    isOrc,
    relentlessEnduranceUses,
    setRelentlessEnduranceUses,
    setShowRelentlessModal,
    isGoliath,
    goliathAncestryUses,
    setPendingGoliathDamageInfo,
    setVictoryData,
    setDroppedLoot
  });

  return {
    isHeroDead,
    processDamageAndCheckKill,
    canvasRef,
    minimapRef,
    activeRevelation,
    setActiveRevelation,
    // Game settings
    isAmbientSoundEnabled,
    setIsAmbientSoundEnabled,
    isSfxEnabled,
    setIsSfxEnabled,
    isShowMinimap,
    setIsShowMinimap,
    isShowZoomControls,
    setIsShowZoomControls,
    // Floating texts
    floatingTexts,
    setFloatingTexts,
    // Logs
    logs,
    setLogs,
    addCombatLog,
    // Arena Exploration
    biome,
    setBiome,
    grid,
    setGrid,
    torches,
    setTorches,
    entities,
    setEntities,
    activeEntityIndex,
    activeEntity,
    setActiveEntityIndex,
    currentTurnRound,
    setCurrentTurnRound,
    weather,
    setWeather,
    weatherTime,
    setWeatherTime,
    isNightManual,
    setIsNightManual,
    combatDifficulty,
    setCombatDifficulty,
    isBattleOver,
    setIsBattleOver,
    isVictoryScreenVisible,
    setIsVictoryScreenVisible,
    victoryData,
    setVictoryData,
    droppedLoot,
    setDroppedLoot,
    chests,
    setChests,
    hazards,
    setHazards,
    powerups,
    setPowerUps,
    restPoints,
    setRestPoints,
    pendingRestPointId,
    setPendingRestPointId,
    totalGameTurns,
    setTotalGameTurns,
    movementStepsCount,
    setMovementStepsCount,
    lastMealTurn,
    lastShortRestTurn,
    lastLongRestTurn,
    prevTurns,
    mapStreak,
    setMapStreak,
    isSaving,
    setIsSaving,
    lastEncounterPos,
    setLastEncounterPos,
    processedDeathIdsRef,
    collectedLootIdsRef,
    openedChestIdsRef,
    exploredCellsRef,
    victoryLogged,
    prevHadVisibleMonstersRef,
    initNewCombat,
    addLootItemToInventory,
    collectLootItem,
    openChest,
    useRestPoint,
    useShortRestPoint,
    handleFinishExploration,
    handleClaimLootAndSave,
    expandMapIfNeeded,
    // Roll & Zoom & 3D & Night
    rollAdvantageState,
    setRollAdvantageState,
    zoomLevel,
    setZoomLevel,
    handleZoomIn,
    handleZoomOut,
    handleZoomReset,
    is3dMode,
    setIs3dMode,
    isIndoor,
    isDesert,
    cycleIndex,
    isNightCycle,
    phaseTurn,
    totalMinutesElapsed,
    baseHour,
    totalMinutesFromMidnight,
    normalizedMinutes,
    currentHour,
    currentMinute,
    timeFormatted,
    nightProgress,
    isNight,
    setIsNight,
    timePhaseLabel,
    timePhaseIcon,
    timePhaseColor,
    entitiesRef,
    // Hero Capabilities
    getActiveFeats,
    getHeroLightRadiusInCells,
    heroHasBlindFighting,
    isEntityVisible,
    isEntityVisibleByBlindFightingOnly,
    shouldHideEntityDetails,
    getEntityCover,
    isMonsterDefeated,
    shouldHideMonsterStats,
    isDragonborn,
    breathWeaponMaxUses,
    draconicFlightMaxUses,
    isGoliath,
    largeFormMaxUses,
    breathWeaponDetails,
    luckyMaxPoints,
    hasLuckyFeat,
    goliathAncestryMaxUses,
    isHalfling,
    isHuman,
    isOrc,
    adrenalineRushMaxUses,
    relentlessEnduranceMaxUses,
    isAasimar,
    healingHandsMaxUses,
    celestialRevelationMaxUses,
    secondWindMaxUses,
    actionSurgeMaxUses,
    rageMaxUses,
    channelDivinityMaxUses,
    spellSlotsMax,
    indomitableMaxUses,
    superiorityDiceMaxUses,
    bardicInspirationMaxUses,
    layOnHandsMaxPool,
    focusPointsMaxUses,
    wildShapeMaxUses,
    hasMagicCapability,
    hasSecondWindCapability,
    checkAmmunitionRequirement,
    getCharacterAmmoCount,
    consumeAmmunition,
    consumeThrownWeapon,
    // Actions & Selection
    selectedAction,
    setSelectedAction,
    targetEntityId,
    setTargetEntityId,
    highlightedPath,
    setHighlightedPath,
    selectedAttackIndex,
    setSelectedAttackIndex,
    hasChangedWeaponThisTurn,
    setHasChangedWeaponThisTurn,
    showAttackModal,
    setShowAttackModal,
    showItemModal,
    setShowItemModal,
    showShortRestModal,
    setShowShortRestModal,
    pendingShortRestItem,
    setPendingShortRestItem,
    hitDiceToSpend,
    setHitDiceToSpend,
    isMinimapMinimized,
    setIsMinimapMinimized,
    showLootModal,
    setShowLootModal,
    isFullscreenMap,
    setIsFullscreenMap,
    showSettingsModal,
    setShowSettingsModal,
    proceduralWorldEnabled,
    setProceduralWorldEnabled,
    proceduralBridge,
    showTacticalMindAlertModal,
    setShowTacticalMindAlertModal,
    showRelentlessModal,
    setShowRelentlessModal,
    pendingRelentlessInfo,
    setPendingRelentlessInfo,
    pendingOpportunityAttack,
    setPendingOpportunityAttack,
    pendingTacticalMindInfo,
    setPendingTacticalMindInfo,
    safeZoom,
    cols,
    rows,
    gwmActive,
    setGwmActive,
    sharpshooterActive,
    setSharpshooterActive,
    versatileTwoHandedWeapons,
    setVersatileTwoHandedWeapons,
    isVersatileWeapon,
    getVersatileDamage,
    selectedEntityForPopup,
    setSelectedEntityForPopup,
    isInitialMount,
    showTargetModal,
    setShowTargetModal,
    targetCandidates,
    setTargetCandidates,
    pendingAttackInfo,
    setPendingAttackInfo,
    latestRoll,
    setLatestRoll,
    latestInitiativeRoll,
    setLatestInitiativeRoll,
    activeEffects,
    setActiveEffects,
    triggerAttackVisualEffect,
    usableInventoryItems,
    totalRationsCount,
    characterAttacks,
    currentSelectedAttack,
    heroACDetails,
    combatSummary,
    handleSelectWeapon,
    weaponMasteryInfo,
    hasDamageAncestry,
    breathWeaponUses,
    setBreathWeaponUses,
    showBreathWeaponModal,
    setShowBreathWeaponModal,
    breathWeaponShape,
    setBreathWeaponShape,
    selectedBreathTargets,
    setSelectedBreathTargets,
    secondWindUses,
    setSecondWindUses,
    healingHandsUses,
    setHealingHandsUses,
    celestialRevelationUses,
    setCelestialRevelationUses,
    draconicFlightUses,
    setDraconicFlightUses,
    activeDraconicFlight,
    setActiveDraconicFlight,
    draconicFlightRoundsLeft,
    setDraconicFlightRoundsLeft,
    largeFormUses,
    setLargeFormUses,
    activeLargeForm,
    setActiveLargeForm,
    largeFormRoundsLeft,
    setLargeFormRoundsLeft,
    radiantSoulRoundsLeft,
    setRadiantSoulRoundsLeft,
    showRevelationMenu,
    setShowRevelationMenu,
    goliathAncestryUses,
    setGoliathAncestryUses,
    isTeleportTargetMode,
    setIsTeleportTargetMode,
    pendingGoliathHitInfo,
    setPendingGoliathHitInfo,
    pendingGoliathDamageInfo,
    setPendingGoliathDamageInfo,
    hasHeroicInspiration,
    setHasHeroicInspiration,
    pendingHalflingLuckInfo,
    setPendingHalflingLuckInfo,
    pendingHeroicInspirationInfo,
    setPendingHeroicInspirationInfo,
    adrenalineRushUses,
    setAdrenalineRushUses,
    relentlessEnduranceUses,
    setRelentlessEnduranceUses,
    actionSurgeUses,
    setActionSurgeUses,
    rageUses,
    setRageUses,
    channelDivinityUses,
    setChannelDivinityUses,
    spellSlots,
    setSpellSlots,
    indomitableUses,
    setIndomitableUses,
    superiorityDiceUses,
    setSuperiorityDiceUses,
    bardicInspirationUses,
    setBardicInspirationUses,
    layOnHandsPool,
    setLayOnHandsPool,
    focusPointsUses,
    setFocusPointsUses,
    wildShapeUses,
    setWildShapeUses,
    luckyPoints,
    setLuckyPoints,
    recklessAttackActive,
    setRecklessAttackActive,
    itemQuantities,
    setItemQuantities,
    handleUseLuckyPoint,
    activeAdvantageMode,
    impendingAttackDetails,
    isTwoHandedWeaponLocal,
    isLightWeapon,
    showVictorySummaryModal,
    setShowVictorySummaryModal,
  };
}

export type GamePlatformState = ReturnType<typeof useGamePlatformState>;
