import { Json } from './json';

export interface ClassTables {
  classes: {
    Row: {
      id: string;
      name: string;
      hit_die: string;
      primary_ability: string;
      saving_throw_proficiencies: Json;
      armor_proficiencies: Json;
      weapon_proficiencies: Json;
      tool_proficiencies: Json;
      skill_proficiency_choices: Json;
      starting_equipment_options: Json;
      created_at: string | null;
      subclasses: Json | null;
      icon: string | null;
      description: string | null;
      hit_point_die: string;
      saving_throws: Json;
      skills: string;
      weapons: Json;
      armor: Json;
      tools: Json | null;
      equipment_options: Json;
    };
    Insert: {
      id?: string;
      name: string;
      hit_die?: string;
      primary_ability?: string;
      saving_throw_proficiencies?: Json;
      armor_proficiencies?: Json;
      weapon_proficiencies?: Json;
      tool_proficiencies?: Json;
      skill_proficiency_choices?: Json;
      starting_equipment_options?: Json;
      created_at?: string | null;
      subclasses?: Json | null;
      icon?: string | null;
      description?: string | null;
      hit_point_die?: string;
      saving_throws?: Json;
      skills?: string;
      weapons?: Json;
      armor?: Json;
      tools?: Json | null;
      equipment_options?: Json;
    };
    Update: {
      id?: string;
      name?: string;
      hit_die?: string;
      primary_ability?: string;
      saving_throw_proficiencies?: Json;
      armor_proficiencies?: Json;
      weapon_proficiencies?: Json;
      tool_proficiencies?: Json;
      skill_proficiency_choices?: Json;
      starting_equipment_options?: Json;
      created_at?: string | null;
      subclasses?: Json | null;
      icon?: string | null;
      description?: string | null;
      hit_point_die?: string;
      saving_throws?: Json;
      skills?: string;
      weapons?: Json;
      armor?: Json;
      tools?: Json | null;
      equipment_options?: Json;
    };
  };
  class_progressions: {
    Row: {
      id: string;
      class_id: string;
      level: number;
      proficiency_bonus: number;
      features: Json;
      cantrips_known: number | null;
      spells_known: number | null;
      spell_slots_1: number | null;
      spell_slots_2: number | null;
      spell_slots_3: number | null;
      spell_slots_4: number | null;
      spell_slots_5: number | null;
      spell_slots_6: number | null;
      spell_slots_7: number | null;
      spell_slots_8: number | null;
      spell_slots_9: number | null;
      invocations_known: number | null;
      rage_count: number | null;
      rage_damage: number | null;
      martial_arts: string | null;
      ki_points: number | null;
      unarmored_movement: string | null;
      sneak_attack: string | null;
      sorcery_points: number | null;
      class_specific: Json | null;
    };
    Insert: {
      id?: string;
      class_id: string;
      level: number;
      proficiency_bonus: number;
      features?: Json;
      cantrips_known?: number | null;
      spells_known?: number | null;
      spell_slots_1?: number | null;
      spell_slots_2?: number | null;
      spell_slots_3?: number | null;
      spell_slots_4?: number | null;
      spell_slots_5?: number | null;
      spell_slots_6?: number | null;
      spell_slots_7?: number | null;
      spell_slots_8?: number | null;
      spell_slots_9?: number | null;
      invocations_known?: number | null;
      rage_count?: number | null;
      rage_damage?: number | null;
      martial_arts?: string | null;
      ki_points?: number | null;
      unarmored_movement?: string | null;
      sneak_attack?: string | null;
      sorcery_points?: number | null;
      class_specific?: Json | null;
    };
    Update: {
      id?: string;
      class_id?: string;
      level?: number;
      proficiency_bonus?: number;
      features?: Json;
      cantrips_known?: number | null;
      spells_known?: number | null;
      spell_slots_1?: number | null;
      spell_slots_2?: number | null;
      spell_slots_3?: number | null;
      spell_slots_4?: number | null;
      spell_slots_5?: number | null;
      spell_slots_6?: number | null;
      spell_slots_7?: number | null;
      spell_slots_8?: number | null;
      spell_slots_9?: number | null;
      invocations_known?: number | null;
      rage_count?: number | null;
      rage_damage?: number | null;
      martial_arts?: string | null;
      ki_points?: number | null;
      unarmored_movement?: string | null;
      sneak_attack?: string | null;
      sorcery_points?: number | null;
      class_specific?: Json | null;
    };
  };
  class_level_features: {
    Row: {
      id: string;
      class_id: string;
      level: number;
      name: string;
      action_type: string;
      description: string;
      usage_limit: string | null;
      created_at: string | null;
    };
    Insert: {
      id?: string;
      class_id: string;
      level: number;
      name: string;
      action_type?: string;
      description: string;
      usage_limit?: string | null;
      created_at?: string | null;
    };
    Update: {
      id?: string;
      class_id?: string;
      level?: number;
      name?: string;
      action_type?: string;
      description?: string;
      usage_limit?: string | null;
      created_at?: string | null;
    };
  };
}
